"""Generate src/ezgatr/_csrc/basis_data.h from the .pt multiplication tables.

Run by hand whenever the .pt files change (effectively never — they're algebra
constants). The output header is committed to git so the C++ build does not
depend on this script being available at compile time.
"""
from __future__ import annotations

import hashlib
from pathlib import Path

import torch

REPO = Path(__file__).resolve().parents[1]
BASIS_DIR = REPO / "src/ezgatr/nn/functional/basis"
OUT = REPO / "src/ezgatr/_csrc/basis_data.h"

DUAL_PERM = list(range(15, -1, -1))
DUAL_SIGN = [1, -1, 1, -1, 1, 1, -1, 1, 1, -1, 1, -1, 1, -1, 1, 1]
INNER_SELECTOR = [0, 2, 3, 4, 8, 9, 10, 14]


def load_dense_int8(path: Path) -> torch.Tensor:
    t = torch.load(path, weights_only=True)
    if t.is_sparse:
        t = t.to_dense()
    if not torch.all((t == -1) | (t == 0) | (t == 1)):
        raise SystemExit(f"{path}: values outside {{-1,0,1}} — refusing to pack as int8")
    if tuple(t.shape) != (16, 16, 16):
        raise SystemExit(f"{path}: expected shape (16,16,16), got {tuple(t.shape)}")
    return t.to(torch.int8)


def fmt_3d(name: str, t: torch.Tensor) -> str:
    lines = [f"inline constexpr int8_t {name}[16][16][16] = {{"]
    for i in range(16):
        lines.append(f"    {{  // i={i}")
        for j in range(16):
            row = ", ".join(f"{int(v):2d}" for v in t[i, j].tolist())
            lines.append(f"        {{{row}}},")
        lines.append("    },")
    lines.append("};")
    return "\n".join(lines)


def fmt_1d(name: str, ctype: str, vals: list[int]) -> str:
    body = ", ".join(str(v) for v in vals)
    return f"inline constexpr {ctype} {name}[16] = {{{body}}};"


def main() -> None:
    gp_path = BASIS_DIR / "geometric_product.pt"
    op_path = BASIS_DIR / "outer_product.pt"

    gp = load_dense_int8(gp_path)
    op = load_dense_int8(op_path)

    gp_sha = hashlib.sha256(gp_path.read_bytes()).hexdigest()
    op_sha = hashlib.sha256(op_path.read_bytes()).hexdigest()

    header = f"""// AUTO-GENERATED by scripts/gen_basis_header.py — do not edit.
// Source files (sha256):
//   {gp_path.name}: {gp_sha}
//   {op_path.name}: {op_sha}
#pragma once
#include <cstdint>

namespace ezgatr {{ namespace opt {{

{fmt_3d("GP_BASIS", gp)}

{fmt_3d("OP_BASIS", op)}

{fmt_1d("DUAL_PERM", "int64_t", DUAL_PERM)}
{fmt_1d("DUAL_SIGN", "int8_t", DUAL_SIGN)}
{fmt_1d("INNER_SELECTOR", "int64_t", INNER_SELECTOR)}

}}}}  // namespace ezgatr::opt
"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header)
    print(f"wrote {OUT.relative_to(REPO)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
